---
- name: Getting list of installed packages
  package_facts:
    manager: "auto"

- name: Removing trash such as snaps
  become: true
  snap:
    name: "{{ item }}"
    state: absent
  loop:
  - lxd
  - core20
  - snapd
  when: "'snapd' in ansible_facts.packages"

- name: Remove snapd package
  become: true
  apt:
    name: snapd
    state: absent
    autoremove: true

- name: Upgrade packages
  become: true
  apt:
    upgrade: dist

- name: Server networking configuration
  become: true
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
    reload: true
  notify: Reload UFW service

- name: Copy before.rules
  become: true
  template:
    src: before.rules.j2
    dest: /etc/ufw/before.rules
    owner: root
    group: root
    mode: 0640
  notify: Reload UFW service

- name: Copy ufw file
  become: true
  copy:
    src: ufw
    dest: /etc/default/ufw
    owner: root
    group: root
    mode: 0644
  notify: Reload UFW service

- name: Add firewall rules
  become: true
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    src: 0.0.0.0/0
  loop:
  - { port: 22, proto: tcp }
  - { port: 1194, proto: udp }

- name: Enable UFW
  become: true
  ufw:
    state: enabled