---
- name: Install package OpenVPN-server
  become: true
  apt:
    name: openvpn
    state: latest

- name: Create ta.key
  command: openvpn --genkey secret ta.key
  args:
    chdir: "{{ ansible_facts.env.HOME }}/easy-rsa"
    creates: "{{ ansible_facts.env.HOME }}/easy-rsa/ta.key"

- name: Copy files for server
  become: true
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: true
    owner: root
    group: root
    mode: 0600
  notify: Restart openvpn service
  loop:
  - { src: "{{ ansible_facts.env.HOME }}/easy-rsa/pki/issued/server.crt", dest: "/etc/openvpn/server/server.crt" }
  - { src: "{{ ansible_facts.env.HOME }}/easy-rsa/pki/private/server.key", dest: "/etc/openvpn/server/server.key" }
  - { src: "{{ ansible_facts.env.HOME }}/easy-rsa/pki/ca.crt", dest: "/etc/openvpn/server/ca.crt" }
  - { src: "{{ ansible_facts.env.HOME }}/easy-rsa/ta.key", dest: "/etc/openvpn/server/ta.key" }

- name: Copy openvpn config file
  become: true
  copy:
    src: server.conf
    dest: /etc/openvpn/server/server.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart openvpn service

- name: Start openvpn service
  become: true
  systemd:
    name: openvpn-server@server
    state: started

- name: Create client config directory
  file:
    path: ~/client-configs/{{ item }}
    state: directory
    mode: 0700
  loop:
  - "keys"
  - "files"

- name: Copy files for client configs
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: true
    mode: 0600
  notify: Restart openvpn service
  loop:
  - { src: "{{ ansible_facts.env.HOME }}/easy-rsa/pki/ca.crt", dest: "{{ ansible_facts.env.HOME }}/client-configs/keys/ca.crt" }
  - { src: "{{ ansible_facts.env.HOME }}/easy-rsa/ta.key", dest: "{{ ansible_facts.env.HOME }}/client-configs/keys/ta.key" }

- name: Copy script for make client-configs
  copy:
    src: make_client_config.sh
    dest: "{{ ansible_facts.env.HOME }}/easy-rsa/make_client_config.sh"
    mode: 0774

- name: Copy base config for clients
  template:
    src: base.conf.j2
    dest: "{{ ansible_facts.env.HOME }}/client-configs/base.conf"
    mode: 0644
