---
- name: Install package OpenVPN-server
  become: true
  apt:
    name: openvpn
    state: latest

- name: Create ta.key
  command: openvpn --genkey secret ta.key
  args:
    chdir: "{{ ansible_facts.env.HOME }}/easy-rsa"
    creates: "{{ ansible_facts.env.HOME }}/easy-rsa/ta.key"

- name: Copy server.crt
  become: true
  copy:
    src: "{{ ansible_facts.env.HOME }}/easy-rsa/pki/issued/server.crt"
    dest: /etc/opencpn/server/
    remote_src: true
    owner: root
    group: root
    mode: 0644

- name: Copy server.key
  become: true
  copy:
    src: "{{ ansible_facts.env.HOME }}/easy-rsa/pki/private/server.key"
    dest: /etc/opencpn/server/
    remote_src: true
    owner: root
    group: root
    mode: 0644

- name: Copy ca.crt
  become: true
  copy:
    src: "{{ ansible_facts.env.HOME }}/easy-rsa/pki/ca.crt"
    dest: /etc/opencpn/server/
    remote_src: true
    owner: root
    group: root
    mode: 0644

- name: Copy ta.key
  become: true
  copy:
    src: "{{ ansible_facts.env.HOME }}/easy-rsa/ta.key"
    dest: /etc/opencpn/server/
    remote_src: true
    owner: root
    group: root
    mode: 0644

- name: Copy openvpn config file
  become: true
  copy:
    src: server.conf
    dest: /etc/openvpn/server/server.conf
    owner: root
    group: root
    mode: 0644
